//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ussdtester.ussdapi {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PegasusUssdSoap", Namespace="http://PegasusUssd/")]
    public partial class PegasusUssd : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessUssdRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PegasusUssd() {
            this.Url = "http://localhost:33749/PegasusUssd.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessUssdRequestCompletedEventHandler ProcessUssdRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://PegasusUssd/ProcessUssdRequest", RequestNamespace="http://PegasusUssd/", ResponseNamespace="http://PegasusUssd/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response ProcessUssdRequest(Request request) {
            object[] results = this.Invoke("ProcessUssdRequest", new object[] {
                        request});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessUssdRequestAsync(Request request) {
            this.ProcessUssdRequestAsync(request, null);
        }
        
        /// <remarks/>
        public void ProcessUssdRequestAsync(Request request, object userState) {
            if ((this.ProcessUssdRequestOperationCompleted == null)) {
                this.ProcessUssdRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessUssdRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessUssdRequest", new object[] {
                        request}, this.ProcessUssdRequestOperationCompleted, userState);
        }
        
        private void OnProcessUssdRequestOperationCompleted(object arg) {
            if ((this.ProcessUssdRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessUssdRequestCompleted(this, new ProcessUssdRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegasusUssd/")]
    public partial class Request {
        
        private string statusDescField;
        
        private string statusCodeField;
        
        private string shortCodeField;
        
        private string networkField;
        
        private string calledNmberField;
        
        private string actionField;
        
        private string requestStringField;
        
        private string clientIdField;
        
        private string trandactionDateField;
        
        private string transactionIdField;
        
        /// <remarks/>
        public string StatusDesc {
            get {
                return this.statusDescField;
            }
            set {
                this.statusDescField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ShortCode {
            get {
                return this.shortCodeField;
            }
            set {
                this.shortCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Network {
            get {
                return this.networkField;
            }
            set {
                this.networkField = value;
            }
        }
        
        /// <remarks/>
        public string CalledNmber {
            get {
                return this.calledNmberField;
            }
            set {
                this.calledNmberField = value;
            }
        }
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string RequestString {
            get {
                return this.requestStringField;
            }
            set {
                this.requestStringField = value;
            }
        }
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string TrandactionDate {
            get {
                return this.trandactionDateField;
            }
            set {
                this.trandactionDateField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://PegasusUssd/")]
    public partial class Response {
        
        private string accountExpectedField;
        
        private string readMethodField;
        
        private string printField;
        
        private string printTextField;
        
        private string actionField;
        
        private string responseStringField;
        
        private string clientIdField;
        
        private string transactionIdField;
        
        private string printCountField;
        
        /// <remarks/>
        public string AccountExpected {
            get {
                return this.accountExpectedField;
            }
            set {
                this.accountExpectedField = value;
            }
        }
        
        /// <remarks/>
        public string ReadMethod {
            get {
                return this.readMethodField;
            }
            set {
                this.readMethodField = value;
            }
        }
        
        /// <remarks/>
        public string Print {
            get {
                return this.printField;
            }
            set {
                this.printField = value;
            }
        }
        
        /// <remarks/>
        public string PrintText {
            get {
                return this.printTextField;
            }
            set {
                this.printTextField = value;
            }
        }
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseString {
            get {
                return this.responseStringField;
            }
            set {
                this.responseStringField = value;
            }
        }
        
        /// <remarks/>
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string PrintCount {
            get {
                return this.printCountField;
            }
            set {
                this.printCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ProcessUssdRequestCompletedEventHandler(object sender, ProcessUssdRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessUssdRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessUssdRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591